/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.actum.portlet.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the News service. Represents a row in the &quot;news_News&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cz.actum.portlet.model.impl.NewsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cz.actum.portlet.model.impl.NewsImpl</code>.
 * </p>
 *
 * @author Andrey
 * @see News
 * @generated
 */
@ProviderType
public interface NewsModel extends BaseModel<News> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a news model instance should use the {@link News} interface instead.
	 */

	/**
	 * Returns the primary key of this news.
	 *
	 * @return the primary key of this news
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this news.
	 *
	 * @param primaryKey the primary key of this news
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this news.
	 *
	 * @return the ID of this news
	 */
	public long getId();

	/**
	 * Sets the ID of this news.
	 *
	 * @param id the ID of this news
	 */
	public void setId(long id);

	/**
	 * Returns the title of this news.
	 *
	 * @return the title of this news
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this news.
	 *
	 * @param title the title of this news
	 */
	public void setTitle(String title);

	/**
	 * Returns the body of this news.
	 *
	 * @return the body of this news
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this news.
	 *
	 * @param body the body of this news
	 */
	public void setBody(String body);

	/**
	 * Returns the date of this news.
	 *
	 * @return the date of this news
	 */
	public Date getDate();

	/**
	 * Sets the date of this news.
	 *
	 * @param date the date of this news
	 */
	public void setDate(Date date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(cz.actum.portlet.model.News news);

	@Override
	public int hashCode();

	@Override
	public CacheModel<cz.actum.portlet.model.News> toCacheModel();

	@Override
	public cz.actum.portlet.model.News toEscapedModel();

	@Override
	public cz.actum.portlet.model.News toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}